// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import("element-plus/es")["ElAside"]
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"]
    ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"]
    ElCol: typeof import("element-plus/es")["ElCol"]
    ElContainer: typeof import("element-plus/es")["ElContainer"]
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"]
    ElDialog: typeof import("element-plus/es")["ElDialog"]
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import("element-plus/es")["ElHeader"]
    ElIcon: typeof import("element-plus/es")["ElIcon"]
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import("element-plus/es")["ElMain"]
    ElMenu: typeof import("element-plus/es")["ElMenu"]
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"]
    ElMenuItemGroup: typeof import("element-plus/es")["ElMenuItemGroup"]
    ElOption: typeof import("element-plus/es")["ElOption"]
    ElOptionGroup: typeof import("element-plus/es")["ElOptionGroup"]
    ElRadio: typeof import("element-plus/es")["ElRadio"]
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"]
    ElSelect: typeof import("element-plus/es")["ElSelect"]
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"]
    ElSwitch: typeof import("element-plus/es")["ElSwitch"]
    ElTable: typeof import("element-plus/es")["ElTable"]
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"]
    ElTimePicker: typeof import("element-plus/es")["ElTimePicker"]
    Form: typeof import('./src/components/form.vue')['default']
    Menu: typeof import('./src/components/menu.vue')['default']
    MenuItem: typeof import('./src/components/menuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
